### ISSUE TITLE
Support dynamic acceleration

### ISSUE THREAD

**Issue by marius-meissner** [Open-GForce/trainer#9]
Instead of static acceleration values, dynamic acceleration in relation to target speed should be set.
For smooth start-up a static soft acceleration needs to be applied until a certain threshold speed (e.g. 0.5G is applied) is reached.

All parameters should be configurable via the web interface.

**Comment by SkydiveMarius** [comment]
Feature is working in operation. As a experiment we should try to use differential speed value for determining the acceleration value.
